### ISSUE TITLE
Add author of course to review cards in wireframe

### ISSUE THREAD

**Issue by Noahliberty** [chingu-voyages/v13-geckos-team-04#1]
Add author of course to review cards in wireframe

**Comment by vansi42** [comment]
@Noahliberty Do you mean add the authors for each course in the list? In the homepage?

**Comment by vansi42** [comment]
Added author to detailed course view

**Comment by Noahliberty** [comment]
Oh yeah if we display it on the homepage I'm not sure if it's neccesarty. Defo in the form to create though as it maybe be a good option to filter later on.

**Comment by vansi42** [comment]
Added author field to new course wireframe
